baseurl      = "https://www.soumyajyotiii.com/"
title        = "blog"
languageCode = "en-us"
theme        = "hugo-theme-hello-friend-ng"
pluralizelisttitles = false

PygmentsCodeFences = true
PygmentsStyle = "monokai"

paginate     = 10
rssLimit  = 10  # Maximum number of items in the RSS feed.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpired = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[permalinks]
  posts = "/posts/:year/:month/:title/"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = """
  Soumyajyoti here, and I'm like the charecter from a feel good movie. Occassionaly you can see me nerding out
   and ranting on computer stuff. My 5-9 after my 9-5 generally consists of me drooling over satisfying Chiropractic ASMR videos ðŸ¤ª"""

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true
  
  # Show a global language switcher in the navigation bar  
  enableGlobalLanguageMenu = true

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

    [params.portrait]
    path = "/images/avatartion.png"
    alt = "Soumyajyoti"
    maxWidth = "150px"


[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    tabTitle = "Soumyajyoti"
    title = "Hey! ðŸ‘‹ðŸ‘‹ "
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

  [languages.en.params]

    [languages.en.params.logo]
      logoText = "#root~$"
      logoHomeLink = "/"
    # or##
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu


[[params.social]]
  name = "github"
  url = "https://github.com/sjm289"

[[params.social]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/soumyajyoti-devops/"

[[params.social]]
  name = "email"
  url = "mailto:soumyajyoti.1999@gmail.com"


[[params.social]]
  name = "instagram"
  url = "https://www.instagram.com/soumyajyotiii/"

[menu]
  [[menu.main]]
    identifier = "candid"
    name       = "candid"
    url        = "candid/"
  [[menu.main]]
    identifier = "tech"
    name       = "tech"
    url        = "tech/"

 

